### ISSUE TITLE
Redirects to http

### ISSUE THREAD

**Issue by xypnox** [sahil-shubham/sahil-shubham.github.io#2]
https://sahil-shubham.github.io/ -> http://sahil-shubham.in/
It should redirect to https://sahil-shubham.in/
Also  http://sahil-shubham.in/ should -> https://sahil-shubham.in

**Comment by sahil-shubham** [comment]
Fixed it, had to enforce HTTPS in GitHub Pages. Thanks for pointing this out. 

Closing this now.
